### PR TITLE
#12 Started securing the env vars

### PR DESCRIPTION
**Pull request by nmunro**
#12 Started securing the env vars, this is in anticipation for both dev and production environments.

### CODE REVIEW

**Review by echarlotte612 — APPROVED** [review]
Party!

**Review by tamjankowska — APPROVED** [review]
Wooop wooop!

**Comment by nmunro** [comment]
I need to fix that test first XD

**Comment by tamjankowska** [comment]
Hey, look, we're just excited, okay?

**Comment by nmunro** [comment]
@tamjankowska @echarlotte612 would you kindly...?

**Comment by tamjankowska** [comment]
Mate, why you pushing secrets tho?

**Comment by nmunro** [comment]
I'm not, this PR is actually removing them...

**Review by tamjankowska — APPROVED** [review]
I'll let you off.

**Pull request merged**
